CREATE DATABASE ecom_sales;

USE ecom_sales;

SELECT * FROM customer_behaviour_analysis;

--1)Which category generates the highest revenue

select 
category,
round(sum(purchase_amount),2) as highest_sales 
from customer_behaviour_analysis
group by category
order by highest_sales desc;

--2)Are discounts actually incrasing the purchase value 
select * from customer_behaviour_analysis;

select discount_applied,
round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by discount_applied
order by total_revenue desc;

--3)what is the total revenue generated by male and female category 
select gender,
round(sum(purchase_amount),2) as revenue_generated
from customer_behaviour_analysis
group by gender
order by revenue_generated desc;

--4)which customer used discount but still spent more than the average purchase amount 
select customer_id,
discount_applied,
purchase_amount 
from customer_behaviour_analysis
where discount_applied= 'Yes' AND purchase_amount >(select avg(purchase_amount) from customer_behaviour_analysis)

--5)which are the top/bottom 5 products which have the highest average review rating 
select top 5
item_purchased,
avg(review_rating) as average_review_rating
from customer_behaviour_analysis
group by item_purchased
order by average_review_rating desc;

select top 5
item_purchased,
avg(review_rating) as average_review_rating
from customer_behaviour_analysis
group by item_purchased
order by average_review_rating asc;

--6)Average purchase : Standard vs Shipping 
select 
shipping_type,
count(distinct(customer_id)) as total_purchase,
round(avg(purchase_amount),2) as average_purchase_amount
from customer_behaviour_analysis
where shipping_type in('Express','Standard')
group by shipping_type

--7)do subscribed customer spends more ? compare the average and the total revenue between subscriber and non-subscriber
select subscription_status,
count(distinct(customer_id)) as total_customers,
round(avg(purchase_amount),2) as average_purchase, 
round(sum(purchase_amount),2) as total_purchase
from customer_behaviour_analysis
group by subscription_status;

--8) top 5 products with highest discount usage
select top 5
item_purchased,
count(item_purchased) as total_count,
count(case when discount_applied='Yes' then 1 end) as total_times_discount_applied,
count(case when discount_applied='Yes' then 1 end)100.0/count() as total_percentage 
from customer_behaviour_analysis
group by item_purchased
order by total_percentage desc;


--9)segments the customers based on the previous purchase like loyal,new,returning customers
select 
case 
	when previous_purchases='0' then 'new customers'
	when previous_purchases between '1' and '15' then 'returning customers'
  else 'loyal customers'
end as customer_segments,
count(*) as total_count
from customer_behaviour_analysis
group by case 
	when previous_purchases='0' then 'new customers'
	when previous_purchases between '1' and '15' then 'returning customers'
  else 'loyal customers'
end 

--10)top 3 products from each category
with cte as(
select 
category,
item_purchased,
count(item_purchased) as total_count,
rank()over(partition by category order by count(item_purchased) desc) as rnk
from customer_behaviour_analysis
group by category,item_purchased
)
select * from cte where rnk<=3

--11)are customers whon are frequent buyers(more than 5 previous purchase)are likely to susbcribe ?
select 
case 
when previous_purchases >5 then 'repeat buyers'
else 'normal buyers'
end as customer_type,
count(*) as total_count
from customer
group by case 
when previous_purchases> 5 then 'repeat buyers'
else 'normal buyers'
end

select 
case 
when previous_purchases >5 then 'repeat buyers'
else 'normal buyers'
end as customer_type,
subscription_status,
count(*) as total_count
from customer_behaviour_analysis
group by case 
when previous_purchases> 5 then 'repeat buyers'
else 'normal buyers'
end,subscription_status

--12)revenue contribution of each age group
select 
case
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '51+'
end as age_grroup,
round(sum(purchase_amount),2) as total_revenue

from customer_behaviour_analysis
group by case
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '51+'
end
order by total_revenue desc;
